---
http_interactions:
- request:
    method: post
    uri: https://owner-api.teslamotors.com/oauth/token
    body:
      encoding: UTF-8
      string: grant_type=password&client_id=<TESLA_CLIENT_ID>&client_secret=<TESLA_CLIENT_SECRET>&email=<TESLA_EMAIL>&password=<TESLA_PASS>
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx
      Date:
      - Wed, 17 Dec 2014 00:28:01 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Status:
      - 200 OK
      Cache-Control:
      - no-store
      Pragma:
      - no-cache
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      X-Request-Id:
      - 7d9a2c5763b750fb7b416a7671bc1676
      X-Runtime:
      - '0.507313'
    body:
      encoding: UTF-8
      string: '{"access_token":"5f423fa2d3c1886006c801d9e3a14388f8f196cdab2b503af7dba983a2d4c796","token_type":"bearer","expires_in":7776000}'
    http_version: 
  recorded_at: Wed, 17 Dec 2014 00:28:03 GMT
- request:
    method: get
    uri: https://owner-api.teslamotors.com/api/1/vehicles
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer 5f423fa2d3c1886006c801d9e3a14388f8f196cdab2b503af7dba983a2d4c796
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx
      Date:
      - Wed, 17 Dec 2014 00:28:01 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '446'
      Connection:
      - keep-alive
      Status:
      - 200 OK
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Etag:
      - '"c5d083718f906b7336fb8b28fcc87b6c"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 2ceef794128248e70e7ae3a78d1213f4
      X-Runtime:
      - '0.078230'
    body:
      encoding: UTF-8
      string: '{"response":[{"color":null,"display_name":"Nikola","id":1514029006966957156,"option_codes":"MS01,RENA,TM00,DRLH,PF00,BT85,PBCW,RFPO,WT19,IBMB,IDPB,TR00,SU01,SC01,TP01,AU01,CH00,HP00,PA00,PS00,AD02,X020,X025,X001,X003,X007,X011,X013,COUS","vehicle_id":490215852,"vin":"5YJSA1CN5CFP01657","tokens":["6b6e59059375f282","09b1673648be8c08"],"state":"online","remote_start_enabled":true,"calendar_enabled":true,"notifications_enabled":true}],"count":1}'
    http_version: 
  recorded_at: Wed, 17 Dec 2014 00:28:03 GMT
- request:
    method: get
    uri: https://owner-api.teslamotors.com/api/1/vehicles/1514029006966957156/data_request/gui_settings
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer 5f423fa2d3c1886006c801d9e3a14388f8f196cdab2b503af7dba983a2d4c796
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx
      Date:
      - Wed, 17 Dec 2014 00:28:02 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '156'
      Connection:
      - keep-alive
      Status:
      - 200 OK
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Etag:
      - '"244167fd8d1d060ffabae9da87cac508"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 950c8b8571324a2a1f8f1c6f1f39d906
      X-Runtime:
      - '0.209955'
    body:
      encoding: UTF-8
      string: '{"response":{"gui_distance_units":"mi/hr","gui_temperature_units":"F","gui_charge_rate_units":"mi/hr","gui_24_hour_time":false,"gui_range_display":"Rated"}}'
    http_version: 
  recorded_at: Wed, 17 Dec 2014 00:28:04 GMT
recorded_with: VCR 2.9.3
